FROM node:latest as docker

WORKDIR /opt

COPY package.* /opt/

RUN npm install

COPY . .

EXPOSE 3005

CMD [ "npm", "start" ]

FROM nginx:latest 

COPY --from=docker /opt /usr/share/nginx/html/

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

