FROM node:latest

WORKDIR /opt

# Install Nginx
RUN apt-get update && apt-get install -y nginx

COPY package.* /opt/
RUN npm install
COPY . .

# Copy the Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Expose only port 80
EXPOSE 80

# Start both Node.js and Nginx
CMD ["sh", "-c", "node app.js & nginx -g 'daemon off;'"]

